"""Add admin_barangay_id to users table

Revision ID: 7a529873d424
Revises: 20260306_scoped_announcements
Create Date: 2026-01-17 13:06:26.776618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '7a529873d424'
down_revision = '20260306_scoped_announcements'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barangays', schema=None) as batch_op:
        batch_op.alter_column('psgc_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # Check if constraint exists before trying to drop it
    conn = op.get_bind()
    inspector = inspect(conn)
    constraints = [c['name'] for c in inspector.get_unique_constraints('municipalities')]
    has_old_constraint = 'uq_municipality_province_name' in constraints

    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        # Only drop if it exists
        if has_old_constraint:
            batch_op.drop_constraint('uq_municipality_province_name', type_='unique')
        # Create unique constraint on name column
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('refresh_token_families', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_token_families_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_tokens_family_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'refresh_token_families', ['family_id'], ['id'])

    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_barangay_id', sa.Integer(), nullable=False))
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'barangays', ['to_barangay_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_barangay_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barangays', ['admin_barangay_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_barangay_id')

    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('to_barangay_id')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('refresh_tokens_family_id_fkey'), 'refresh_token_families', ['family_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('refresh_token_families', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('refresh_token_families_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_municipality_province_name'), ['province_id', 'name'])

    with op.batch_alter_table('barangays', schema=None) as batch_op:
        batch_op.alter_column('psgc_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
