#!/usr/bin/env python3
"""
MunLink - Setup Network Environment Variables
This script detects your local IP and creates .env files for frontend apps
"""
import os
import socket
from pathlib import Path

def get_local_ip():
    """Get the local IP address"""
    try:
        # Connect to a remote address (doesn't actually send data)
        # This method works on Windows, Linux, and macOS
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        # Fallback: try to get from hostname
        try:
            hostname = socket.gethostname()
            ip = socket.gethostbyname(hostname)
            if ip.startswith("127."):
                return None
            return ip
        except Exception:
            return None

def main():
    print("Setting up network access configuration...")
    
    # Get project root (parent of scripts directory)
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    # Get IP address
    ip_address = get_local_ip()
    
    if not ip_address:
        print("Warning: Could not detect IP address. Using localhost.")
        ip_address = "localhost"
    else:
        print(f"Detected local IP address: {ip_address}")
    
    # Create .env files
    web_env_path = project_root / "apps" / "web" / ".env"
    admin_env_path = project_root / "apps" / "admin" / ".env"
    
    api_url = f"http://{ip_address}:5000"
    
    # Create web .env
    web_content = f"""# Auto-generated by setup_network_env.py
# API URL for network access
VITE_API_URL={api_url}
"""
    
    # Create admin .env
    admin_content = f"""# Auto-generated by setup_network_env.py
# API URL for network access
VITE_API_URL={api_url}
VITE_API_BASE_URL={api_url}
"""
    
    try:
        web_env_path.write_text(web_content, encoding='utf-8')
        print(f"Created: {web_env_path.relative_to(project_root)}")
    except Exception as e:
        print(f"Failed to create {web_env_path}: {e}")
    
    try:
        admin_env_path.write_text(admin_content, encoding='utf-8')
        print(f"Created: {admin_env_path.relative_to(project_root)}")
    except Exception as e:
        print(f"Failed to create {admin_env_path}: {e}")
    
    print("")
    print("Network configuration complete!")
    print(f"API URL: {api_url}")
    print("")
    print("Access URLs:")
    print(f"  Frontend Web:  http://{ip_address}:3000")
    print(f"  Admin Panel:   http://{ip_address}:3001")
    print(f"  API:           {api_url}")
    print("")

if __name__ == "__main__":
    main()


