# MunLink - Setup Network Environment Variables
# This script detects your local IP and creates .env files for frontend apps

Write-Host "Setting up network access configuration..." -ForegroundColor Yellow

# Get the script directory (project root)
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Find local IP address
$ipAddress = $null
try {
    $ipAddress = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {
        $_.IPAddress -notlike "127.*" -and 
        $_.IPAddress -notlike "169.254.*" -and
        $_.PrefixOrigin -eq "Dhcp"
    } | Select-Object -First 1).IPAddress
} catch {
    # Fallback method
    try {
        $ipAddress = (Get-NetIPConfiguration | Where-Object {
            $_.IPv4Address.IPAddress -notlike "127.*" -and
            $_.IPv4Address.IPAddress -notlike "169.254.*"
        } | Select-Object -First 1).IPv4Address.IPAddress
    } catch {
        Write-Host "Could not automatically detect IP address. Using localhost." -ForegroundColor Yellow
        $ipAddress = "localhost"
    }
}

if (-not $ipAddress) {
    Write-Host "Warning: Could not detect IP address. Using localhost." -ForegroundColor Yellow
    $ipAddress = "localhost"
} else {
    Write-Host "Detected local IP address: $ipAddress" -ForegroundColor Green
}

# Create .env files for frontend apps
$webEnvPath = Join-Path $scriptDir "apps\web\.env"
$adminEnvPath = Join-Path $scriptDir "apps\admin\.env"

$apiUrl = "http://$ipAddress`:5000"

# Create web .env
$webEnvContent = @"
# Auto-generated by setup_network_env.ps1
# API URL for network access
VITE_API_URL=$apiUrl
"@

# Create admin .env
$adminEnvContent = @"
# Auto-generated by setup_network_env.ps1
# API URL for network access
VITE_API_URL=$apiUrl
VITE_API_BASE_URL=$apiUrl
"@

try {
    Set-Content -Path $webEnvPath -Value $webEnvContent -Force
    Write-Host "Created: apps\web\.env" -ForegroundColor Green
} catch {
    Write-Host "Failed to create apps\web\.env: $_" -ForegroundColor Red
}

try {
    Set-Content -Path $adminEnvPath -Value $adminEnvContent -Force
    Write-Host "Created: apps\admin\.env" -ForegroundColor Green
} catch {
    Write-Host "Failed to create apps\admin\.env: $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "Network configuration complete!" -ForegroundColor Green
Write-Host "API URL: $apiUrl" -ForegroundColor Cyan
Write-Host ""
Write-Host "Access URLs:" -ForegroundColor Yellow
Write-Host "  Frontend Web:  http://$ipAddress`:3000" -ForegroundColor Cyan
Write-Host "  Admin Panel:   http://$ipAddress`:3001" -ForegroundColor Cyan
Write-Host "  API:           $apiUrl" -ForegroundColor Cyan
Write-Host ""




